# Generated by Django 5.2.3 on 2026-02-09 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameresult',
            name='player_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
