# Generated by Django 5.2.3 on 2026-02-09 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0002_gameresult_player_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameresult',
            name='player_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
