# Generated by Django 5.2.3 on 2026-02-10 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0003_gameresult_player_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lobby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('host_email', models.EmailField(max_length=254)),
                ('host_name', models.CharField(max_length=255)),
                ('status', models.CharField(default='WAITING', max_length=20)),
                ('settings', models.JSONField(default=dict)),
                ('players_data', models.JSONField(default=list)),
                ('results_data', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='gameresult',
            name='player_phone',
        ),
    ]
