# Generated by Django 5.2.3 on 2026-02-11 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0002_add_performance_indexes'),
        ('hackathon', '0004_lobby_remove_gameresult_player_phone'),
    ]

    operations = [
    ]
